### ISSUE TITLE
RE: (#107) - GUI NaN in variables

### ISSUE THREAD

**Issue by cmachingauta** [sdcTools/sdcMicro#112]
Hi Bernhard, I just tested and I see that the NAs are now excluded from the 'Select levels to recode/combine' box. Is it possible to have them show up there as well, in case there is a situation where they need to be combined with another level or recoded as well? Thanks for adding the value labels.c

**Comment by bernhard-da** [comment]
Thx for reporting. Could you please check and report back, if everything works as expected after the latest changes so that we can close this issue? Thx.

**Comment by cmachingauta** [comment]
I tested, this has been solved, I can see the NAs now. Thank you!

**Comment by cmachingauta** [comment]
This was fixed when I tested, but seems to have reverted back to excluding NAs from recode/combine option. Please fix.  Thanks

**Comment by bernhard-da** [comment]
I did not change anything after closing this issue. Please provide exact data/steps what you did when you saw this issue again.

**Comment by mwelch750** [comment]
Cathrine, 
The problem is back for me too. (On Linux, mac and windows) Could you send the caseA.dta file to bernhard and the output from the script in your reproducibility screen too?

**Comment by cmachingauta** [comment]
CaseA data is already in Box, so I will send the output from the screen on the reproducibility tab.

**Comment by cmachingauta** [comment]
Hi, it seems to go back and forth between showing NAs and not.  I attach the scripts here, and I have also uploaded the videos and on Box. All I do is load the datasets (CaseA and CaseB), EDUCY is the same in both datasets, same number of NAs. In the video WithNAs you will see that I cannot select the NA for recoding/combining although the NA category appears at the bottom of the list.  
[NoNAs.txt](https://github.com/alexkowa/sdcMicro/files/564797/NoNAs.txt)
[WithNAs.txt](https://github.com/alexkowa/sdcMicro/files/564798/WithNAs.txt)

**Comment by bernhard-da** [comment]
Thx for the feedback. Previously, recoding of NAs was only possible for inputdata. I changed the behaviour that it is now also possible once a problem instance has been generated.

Please test and report back.

**Comment by cmachingauta** [comment]
I tested with both datasets and it seems to work now. Thanks
